server:
  port: 2020
spring:
  application:
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://localhost:3306/sob_blog_system?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码

sob.blog.image.save-path: E:\project\IdeaProject\SobBlogSystem\images

# 2mb
sob.blog.image.max-size: 2097152